version: '3.5'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    stdin_open: true
    tty: true        
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    expose:
      - 3306
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    expose:
      - 9000
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

volumes:
  db:
    driver: local
    driver_opts:
      device: /home/eportela/mariadb
      o: bind
      type: none
  wordpress:
    driver: local
    driver_opts:
      device: /home/eportela/wordpress
      o: bind
      type: none

networks:
  inception:
    driver: bridge
