version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    image: nginx:42
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file:
      - .env
    image: mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_build: wordpress
    build: ./requirements/wordpress/
    env_file:
      - .env
    image: wordpress:42
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

volumes:
    mariadb:
      name: mariadb
      driver: local
      driver_opts:
      device: Users/eportela/Desktop/Inception/mariadb 
      o: bind
      type: none
    wordpress:
      name: wordpress
      driver: local
      driver_opts: Users/eportela/Desktop/Inception/wordpress
      device:
      o: bind
      type: none

networks:
  inception:
      name: inception
